#!/bin/bash -e

#
# cd to proj/hydra-whatever or proj/hydra_whatever in that priority
#

BASE="$PROJECTS/hydra/hydra"

PROJ="$1"
DIRS=(${BASE}-${PROJ} ${BASE}_${PROJ})
SUCCESS=false

for d in $DIRS; do
  if [ -d "$d" ]; then
    cd "$d"
    SUCCESS=true
    break
  fi
done

if $SUCCESS; then
else
  echo "no such directories: $DIRS"
fi
